name: climateGPT
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.12.7=ha878542_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py38h06a4308_0
  - cryptography=39.0.1=py38h9ce1e76_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.1.55=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - dataclasses-json=0.5.7=pyhd8ed1ab_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py38h5eee18b_0
  - gds-tools=1.6.0.25=0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gptcache=0.1.21=pyhd8ed1ab_0
  - idna=3.4=py38h06a4308_0
  - importlib-metadata=6.0.0=py38h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py38hb070fc8_0
  - ipython=8.12.0=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.1.0=py38h06a4308_0
  - jupyter_core=5.3.0=py38h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.6.0.25=0
  - libcufile-dev=1.6.0.25=0
  - libcurand=10.3.2.56=0
  - libcurand-dev=10.3.2.56=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - marshmallow=3.19.0=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - nsight-compute=2023.1.0.15=0
  - numexpr=2.8.4=py38he184ba9_0
  - numpy=1.24.3=py38h14f4228_0
  - numpy-base=1.24.3=py38h31eccc5_0
  - openapi-schema-pydantic=1.2.4=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openpyxl=3.0.9=pyhd8ed1ab_0
  - openssl=1.1.1t=h7f8727e_0
  - pandas-stubs=2.0.0.230412=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py38h6a678d5_0
  - pip=23.0.1=py38h06a4308_0
  - platformdirs=2.5.2=py38h06a4308_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.13.1=py3.8_cuda11.6_cudnn8.3.2_0
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_4
  - pyzmq=25.0.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py38h06a4308_0
  - setuptools=66.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - stringcase=1.2.0=py_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.13.1=py38_cu116
  - torchvision=0.14.1=py38_cu116
  - tornado=6.2=py38h5eee18b_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.7.1=py38h06a4308_0
  - types-pytz=2023.3.0.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=py38h06a4308_0
  - typing_extensions=4.5.0=py38h06a4308_0
  - typing_inspect=0.8.0=pyhd8ed1ab_0
  - urllib3=1.26.15=py38h06a4308_0
  - wheel=0.38.4=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==1.4.0
    - accelerate==0.18.0
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - altair==4.2.2
    - anyio==3.6.2
    - appdirs==1.4.4
    - attrs==23.1.0
    - backoff==2.2.1
    - beautifulsoup4==4.12.2
    - chromadb==0.3.21
    - click==8.1.3
    - clickhouse-connect==0.5.22
    - contourpy==1.0.7
    - cycler==0.11.0
    - datasets==2.12.0
    - deepspeed==0.9.0
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - duckdb==0.7.1
    - einops==0.6.1
    - entrypoints==0.4
    - evaluate==0.4.0
    - fastapi==0.95.1
    - ffmpy==0.3.0
    - filelock==3.11.0
    - flash-attn==1.0.2
    - fonttools==4.39.3
    - fschat==0.2.2
    - fsspec==2023.4.0
    - gdown==4.7.1
    - gitdb==4.0.10
    - gitpython==3.1.31
    - gradio==3.23.0
    - greenlet==2.0.2
    - h11==0.14.0
    - hjson==3.1.0
    - hnswlib==0.7.0
    - httpcore==0.17.0
    - httptools==0.5.0
    - httpx==0.24.0
    - huggingface-hub==0.13.4
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - kaggle==1.5.13
    - kiwisolver==1.4.4
    - langchain==0.0.153
    - langdetect==1.0.9
    - linkify-it-py==2.0.0
    - lz4==4.3.2
    - markdown-it-py==2.2.0
    - markdown2==2.4.8
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - monotonic==1.6
    - multidict==6.0.4
    - multiprocess==0.70.14
    - ninja==1.11.1
    - nltk==3.8.1
    - openai==0.27.6
    - orjson==3.8.10
    - packaging==23.1
    - pandas==2.0.0
    - pathtools==0.1.2
    - peft==0.2.0
    - pipreqs==0.4.13
    - pkgutil-resolve-name==1.3.10
    - posthog==3.0.1
    - prompt-toolkit==3.0.38
    - protobuf==4.22.3
    - psutil==5.9.4
    - py-cpuinfo==9.0.0
    - pyarrow==12.0.0
    - pydantic==1.10.7
    - pydub==0.25.1
    - pygments==2.15.0
    - pyparsing==3.0.9
    - pypdf==3.8.1
    - pyrsistent==0.19.3
    - python-dotenv==1.0.0
    - python-multipart==0.0.6
    - python-slugify==8.0.1
    - regex==2023.3.23
    - responses==0.18.0
    - rich==13.3.4
    - rouge==1.0.1
    - rouge-score==0.1.2
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - semantic-version==2.10.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.98
    - sentry-sdk==1.19.1
    - setproctitle==1.3.2
    - shortuuid==1.0.11
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - sqlalchemy==1.4.47
    - starlette==0.26.1
    - svgwrite==1.4.3
    - text-unidecode==1.3
    - threadpoolctl==3.1.0
    - tokenizers==0.13.3
    - toolz==0.12.0
    - transformers==4.29.0.dev0
    - tzdata==2023.3
    - uc-micro-py==1.0.1
    - uvicorn==0.21.1
    - uvloop==0.17.0
    - wandb==0.14.2
    - watchfiles==0.19.0
    - wavedrom==2.0.3.post3
    - wcwidth==0.2.6
    - websockets==11.0.1
    - xxhash==3.2.0
    - yarg==0.1.9
    - yarl==1.8.2
    - zipp==3.15.0
    - zstandard==0.21.0
prefix: /home/sahal.mullappilly/.conda/envs/climateGPT
